# Generated by Django 2.2.3 on 2020-07-28 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='fecha de vencimiento')),
                ('confirmation', models.BooleanField(default=False, verbose_name='confimacion')),
                ('rubro', models.CharField(blank=True, choices=[('VENTAS_ONLINE', 'VENTAS_ONLINE'), ('BLOG', 'BLOG'), ('INFORMATIVA', 'INFORMATIVA'), ('CORPORATIVA', 'CORPORATIVA'), ('OTROS', 'OTROS')], max_length=30, null=True, verbose_name='rubro')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('confirmation', models.BooleanField(default=False, verbose_name='confirmation')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_projects', to='projects.Project')),
            ],
        ),
    ]
