# Generated by Django 2.2.3 on 2020-07-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='confirmation',
            field=models.BooleanField(default=False, verbose_name='confimacion'),
        ),
    ]
