# Generated by Django 2.2.3 on 2020-08-16 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='alcance',
            field=models.TextField(blank=True, null=True, verbose_name='alcance'),
        ),
        migrations.AddField(
            model_name='project',
            name='fuera_alcance',
            field=models.TextField(blank=True, null=True, verbose_name='fuera de alcance'),
        ),
        migrations.AddField(
            model_name='project',
            name='objetivo',
            field=models.TextField(blank=True, null=True, verbose_name='objetivo'),
        ),
        migrations.AddField(
            model_name='project',
            name='objetivos_sistema',
            field=models.TextField(blank=True, null=True, verbose_name='objetivos del sistema'),
        ),
        migrations.AddField(
            model_name='project',
            name='perspectiva_producto',
            field=models.TextField(blank=True, null=True, verbose_name='perspectiva del producto'),
        ),
        migrations.AddField(
            model_name='project',
            name='restricciones',
            field=models.TextField(blank=True, null=True, verbose_name='restricciones'),
        ),
        migrations.AddField(
            model_name='project',
            name='suposiciones_dependencias',
            field=models.TextField(blank=True, null=True, verbose_name='suposiciones y dependencias'),
        ),
        migrations.AddField(
            model_name='project',
            name='vision_general_documento',
            field=models.TextField(blank=True, null=True, verbose_name='vision general del documento'),
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='name')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='projects.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
