# Generated by Django 2.2.3 on 2020-08-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='general_requeriments',
        ),
        migrations.AddField(
            model_name='project',
            name='general_requeriments',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.GeneralRequeriments'),
        ),
    ]
