# Generated by Django 2.2.3 on 2020-07-12 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_auto_20200712_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='confirmation',
            field=models.BooleanField(default=False, verbose_name='confirmation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date_end'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='name'),
        ),
        migrations.CreateModel(
            name='User_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('confirmation', models.BooleanField(default=False, verbose_name='confirmation')),
                ('colaborador', models.CharField(blank=True, choices=[('ADMIN', 'administrador'), ('COLABORATOR', 'colaborador'), ('USER', 'usuario')], max_length=14, null=True, verbose_name='tipo_usuario')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_projects', to='projects.Project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(related_name='users', through='projects.User_Project', to=settings.AUTH_USER_MODEL),
        ),
    ]
