# Generated by Django 2.2.3 on 2020-07-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='direccion'),
        ),
        migrations.AddField(
            model_name='user',
            name='enterprise_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='nombre de empresa'),
        ),
    ]
