# Generated by Django 2.2.3 on 2020-07-12 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200712_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created_at',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_modified',
            new_name='update_date',
        ),
    ]
