# Generated by Django 2.2.3 on 2020-07-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200712_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='dni'),
        ),
    ]
