# Generated by Django 2.2.3 on 2020-08-14 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('confirmation', models.BooleanField(default=False, verbose_name='project_requirements')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_requirements', to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('priority', models.CharField(blank=True, max_length=10, null=True, verbose_name='prioridad')),
                ('cost', models.FloatField(blank=True, null=True, verbose_name='costo')),
                ('creation_date', models.DateTimeField(blank=True, null=True, verbose_name='fecha de creacion')),
                ('show', models.BooleanField(default=False, verbose_name='mostrar')),
                ('projects', models.ManyToManyField(blank=True, related_name='requeriments', through='requirements.Project_Requirement', to='projects.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project_requirement',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_requirements', to='requirements.Requirement'),
        ),
        migrations.AlterUniqueTogether(
            name='project_requirement',
            unique_together={('project', 'requirement')},
        ),
    ]
