# Generated by Django 2.2.3 on 2020-08-16 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200816_1904'),
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='projects.Actor'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='numeracion',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='numeracion'),
        ),
    ]
