# Generated by Django 2.2.3 on 2020-08-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0002_auto_20200816_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='descripcion_detallada',
            field=models.TextField(blank=True, null=True, verbose_name='descripcion_detallada'),
        ),
    ]
